config/routes.rb
Vag::Application.routes.draw do

  match 'user/:user_id' => 'Users#show', :as => 'user'
  resources :user_sessions, :only =>[:new, :create, :destroy]
  resources :sbmessages, :only => [:new, :create]
  resources :avatars
  resources :users do
    resources :cargalleries do
      resources :carimages
    end
  end

  match 'admin', :to => 'Admin#index', :as => 'admin'      
  get 'login', :to => 'User_sessions#new', :as => 'login'
	match 'logout', :to => 'User_sessions#destroy', :as => 'logout'
  get 'register', :to => 'Users#new', :as => 'register'
  
   namespace :admin do    
    resources :users
    resources :images
    resources :avatars
    resources :galleries
    resources :comments
    resources :articles do
      get "act(/:art_act)", :to => "Articles#act", :as => "act"
    end
    resources :sbmessages
  end

  resources :articles do
    resources :comments
  end
  match ':article' => 'Articles#show', :as => 'article' 
   root :to => "Home#index"
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  acts_as_list
  validates :title, :presence => true
  has_many :images
  has_many :galleries
  has_many :comments
  
  def to_param
    "#{id}-#{title.parameterize}"
  end

end

app/models/avatar.rb
class Avatar < ActiveRecord::Base
  belongs_to :user
  
  has_attached_file :photo, :styles => { :vsmall => "70x60>",
                                         :small => "150x150>",
                                         :thumb => "250x250>",
                                         :original => "350x350>"},
 :url  => "/avatars/:id/:style/:basename.:extension",
 :path => ":rails_root/public/avatars/:id/:style/:basename.:extension"

validates_attachment_presence :photo
validates_attachment_size :photo, :less_than => 2.megabytes
validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

end

app/models/cargallery.rb
class Cargallery < ActiveRecord::Base
  belongs_to :user
  has_many :carimages
end

app/models/carimage.rb
class Carimage < ActiveRecord::Base
  belongs_to :cargallery
  acts_as_list :scope => :cargallery
  
    has_attached_file :photo, :styles => {
                                         :vsmall => "150x150>",
                                         :small => "300x300>",
                                         :thumb => "640x480>",
                                         :original => "800x600>"},
 :url  => "/carimages/:id/:style/:basename.:extension",
 :path => ":rails_root/public/carimages/:id/:style/:basename.:extension"

validates_attachment_presence :photo
validates_attachment_size :photo, :less_than => 5.megabytes
validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    validate :body, :presence => :true  
  
  belongs_to :article
  belongs_to :user
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  belongs_to :article
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :article
  belongs_to :gallery
#  acts_as_list :scope => :gallery
  
  has_attached_file :photo, :styles => { :vsmall => "100x100>",
                                         :thumb => "150x150>",
                                         :small => "300x300>",
                                         :oryginal => "800x600>"},
                  :url  => "/gallery/image/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/gallery/image/:id/:style/:basename.:extension"

validates_attachment_presence :photo
validates_attachment_size :photo, :less_than => 5.megabytes
validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/sbmessage.rb
class Sbmessage < ActiveRecord::Base
  validates :message, :presence => true
  validates :user_id, :presence => true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic 
  validate :username, :uniqueness => :true, :on =>  :create
  validate :email, :uniqueness => :true, :on => :create
  has_one :gallery
  has_one :cargallery
  has_one :avatar
  has_many :images
  has_many :comments
  belongs_to :role

  def to_param
    "#{username}"
  end

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  validate :username, :presence => true
  validate :password, :presence => true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'


  def index
  end
  
 
end

app/controllers/cargalleries_controller.rb
class CargalleriesController < ApplicationController
  
  def index
    @user_session = UserSession.new
    @cargalleries = Cargallery.all(:conditions => 
    {:user_id => current_user.id})
    @users_online = User.find(:all, :order => 'last_request_at DESC', :limit => 10)
    @sbmessages = Sbmessage.all(:order => 'created_at DESC', :limit => 20)
  	@sbmessagesTOP = Sbmessage.all(:select => 'user_id, count(message) as top', :group => "user_id", :order => "top DESC", :limit => 5)
  end
  
  def show
    @cargallery = Cargallery.find(params[:id])
    @user = current_user
    @carimage = Carimage.new
    @carimages = Carimage.all(:conditions => {:user_id => User.find_by_username(params[:user_id])}, :order => "position ASC")
    @user_session = UserSession.new
    @users_online = User.find(:all, :order => 'last_request_at DESC', :limit => 10)
    @sbmessages = Sbmessage.all(:order => 'created_at DESC', :limit => 20)
  	@sbmessagesTOP = Sbmessage.all(:select => 'user_id, count(message) as top', :group => "user_id", :order => "top DESC", :limit => 5)
  end
  
  def new
    @user = User.find_by_username(params[:user_id])
    @cargallery = Cargallery.new

    @user_session = UserSession.new
    @users_online = User.find(:all, :order => 'last_request_at DESC', :limit => 10)
    @sbmessages = Sbmessage.all(:order => 'created_at DESC', :limit => 20)
  	@sbmessagesTOP = Sbmessage.all(:select => 'user_id, count(message) as top', :group => "user_id", :order => "top DESC", :limit => 5)
  end
  
  def edit
@users_online = User.find(:all, :order => 'last_request_at DESC', :limit => 10)
@sbmessages = Sbmessage.all(:order => 'created_at DESC', :limit => 20)
@sbmessagesTOP = Sbmessage.all(:select => 'user_id, count(message) as top', :group => "user_id", :order => "top DESC", :limit => 5)
  end
  
  def create
    @cargallery = Cargallery.new(params[:cargallery])
    if @cargallery.save
      redirect_to user_cargalleries_path(params[:user_id])
    else
    end
  end
  
  def update
    @cargallery = Cargallery.find(params[:id])
    if @cargallery.update_attributes(params[:cargallery])
      redirect_to user_cargalleries_path(params[:user_id])  
    else
      redirect_to user_cargalleries_path(params[:user_id])
    end
    
  end 
  
  def destroy
    @cargallery = Cargallery.find(params[:id])
    @cargallery.destroy
    redirect_to user_cargalleries_path(params[:user_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @articles = Article.all(:order => :position, :conditions =>{:publish => true}).paginate(:per_page => 5, :page => params[:page])
    @user_session = UserSession.new
    @users_online = User.find(:all, :order => 'last_request_at DESC', :limit => 10)
    @sbmessages = Sbmessage.all(:order => 'created_at DESC', :limit => 20)
  	@sbmessagesTOP = Sbmessage.all(:select => 'user_id, count(message) as top', :group => "user_id", :order => "top DESC", :limit => 5)

  end
  
end

app/helpers/admin_helper.rb
module AdminHelper
  
    def javascript(*files)
      content_for(:head) { javascript_include_tag(*files) }
    end

    def stylesheet(*files)
      content_for(:head) { stylesheet_link_tag(*files) }
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
    def tag_content(tag)
    content_for(:tag) { "<meta name='keywords' content='#{tag}' />".html_safe}
  end

    def render_gallery(content)
    id = content.scan(/\{gallery=(\d+)\}/)
    if !id.nil?
      id.each do |id|
        partial_content = render :partial => 'share/gallery', :locals => {:id => id[0].to_i }
        content.sub! /\{gallery=\d+\}/, partial_content
      end
      return content.html_safe
    else
      content.gsub! /\{gallery=\d+\}/, ''
      content.html_safe
    end
  end  
    
  
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/cargalleries_helper.rb
module CargalleriesHelper
end

app/helpers/carimages_helper.rb
module CarimagesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sbmessages_helper.rb
module SbmessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cargalleries/edit.html.erb
  <div class="mainbox">
		<div class="mainbox_top">
			<div class="mainbox_top_left"></div>
      <div class="mainbox_top_center"><i>Galeria samochodu</i></div>
			<div class="mainbox_top_right"></div>
		</div>

		<div class="mainbox_left">
			<div class="mainbox_right">
				<div class="mainbox_center">
        <% @user = User.find(current_user.id)%>
        <% @cargallery = Cargallery.find(params[:id])%>
        <%= form_for([@user, @cargallery]) do |f| %>
        Nazwa galerii:<br />
        <%= f.text_field :name %><br />
        Opis galerii: <br />
        <%= f.text_area :describe, :rows => 3 %><br />
        <%= f.submit "Aktualizacja galerii"%>
          <% end %>

        <div class="read_more"><%= link_to "Powrót", user_cargalleries_path(current_user)%></div>
      </div>
			</div>
		</div>

		<div class="mainbox_down">
			<div class="mainbox_down_left"></div>
			<div class="mainbox_down_center"></div>
			<div class="mainbox_down_right"></div>
		</div>
  </div>  

app/views/cargalleries/index.html.erb
  <div class="mainbox">
		<div class="mainbox_top">
			<div class="mainbox_top_left"></div>
      <div class="mainbox_top_center"><i>Galeria samochodu</i></div>
			<div class="mainbox_top_right"></div>
		</div>

		<div class="mainbox_left">
			<div class="mainbox_right">
				<div class="mainbox_center">
        <table>
          <tr>
           <th>Lp</th>
           <th>Nazwa</th>
            <th colspan="3">Options</th>
          </tr>
          <% @cargalleries.each do |cargallery|%>          
          <tr>
            <td>#</td>
            <td><%= cargallery.name %></td>
            <td><%= link_to "Pokaż", user_cargallery_path(current_user.username, cargallery) %></td>
            <td><%= link_to "Edytuj", edit_user_cargallery_path(current_user.username, cargallery) %></td>
            <td><%= link_to "Usuń", user_cargallery_path(current_user.username, cargallery), :method => :delete, :confirm => "tak?" %></td>
          </tr>
          <% end %>
        </table>
<div class="read_more">
        <%= link_to "Dodaj Galerię samochodu", new_user_cargallery_path(current_user.username)%>
</div>
         <div class="read_more"><%= link_to "Powrót", edit_user_path(current_user)%></div>
      </div>
			</div>
		</div>

		<div class="mainbox_down">
			<div class="mainbox_down_left"></div>
			<div class="mainbox_down_center"></div>
			<div class="mainbox_down_right"></div>
		</div>
  </div>  

app/views/cargalleries/new.html.erb
  <div class="mainbox">
		<div class="mainbox_top">
			<div class="mainbox_top_left"></div>
      <div class="mainbox_top_center"><i>Galeria samochodu</i></div>
			<div class="mainbox_top_right"></div>
		</div>

		<div class="mainbox_left">
			<div class="mainbox_right">
				<div class="mainbox_center">
 <%= form_for([@user, @cargallery], :html => { :multipart => true }) do |f| %>
  <%= f.text_field :user_id, :value => User.find_by_username(params[:user_id]).id%>
Nazwa:  <%= f.text_field :name %>
  <%= f.submit "Dodaj Galerię"%>
 <% end %>

        <div class="read_more"><%= link_to "Powrót", user_cargalleries_path(current_user)%></div>
      </div>
			</div>
		</div>

		<div class="mainbox_down">
			<div class="mainbox_down_left"></div>
			<div class="mainbox_down_center"></div>
			<div class="mainbox_down_right"></div>
		</div>
  </div>  

app/views/cargalleries/show.html.erb
  <div class="mainbox">
		<div class="mainbox_top">
			<div class="mainbox_top_left"></div>
      <div class="mainbox_top_center"><i>Galeria samochodu</i></div>
			<div class="mainbox_top_right"></div>
		</div>

		<div class="mainbox_left">
			<div class="mainbox_right">
				<div class="mainbox_center">
<%= form_for([@user, @cargallery, @carimage], :html => { :multipart => true }) do |f| %>
  <%= f.hidden_field :user_id, :value => current_user.id%>
<%= f.hidden_field :cargallery_id, :value => params[:id]%>
<%= f.file_field :photo %><br />
  <%= f.submit "Dodaj zdjęcie"%>
<% end %>
<% @carimages.each do |carimage| %>
  <div>
    <%= image_tag carimage.photo.url(:vsmall)%><br />
    <%= link_to "Usuń", user_cargallery_carimage_path(params[:user_id], params[:id], carimage.id), :method => :delete, :confirm => "tak ?"%>
  </div>
  <% end %>

<div class="read_more"><%= link_to "Powrót", user_cargalleries_path(current_user)%></div>
      </div>
			</div>
		</div>

		<div class="mainbox_down">
			<div class="mainbox_down_left"></div>
			<div class="mainbox_down_center"></div>
			<div class="mainbox_down_right"></div>
		</div>
  </div>  