config/routes.rb
Vag::Application.routes.draw do

  match 'user/:user_id' => 'Users#show', :as => 'user'
  resources :user_sessions, :only =>[:new, :create, :destroy]
  resources :sbmessages, :only => [:new, :create]
  resources :avatars
  resources :users do
    resources :cargalleries do
      resources :carimages
    end
  end

  match 'admin', :to => 'Admin#index', :as => 'admin'      
  get 'login', :to => 'User_sessions#new', :as => 'login'
	match 'logout', :to => 'User_sessions#destroy', :as => 'logout'
  get 'register', :to => 'Users#new', :as => 'register'
  
   namespace :admin do    
    resources :users
    resources :images
    resources :avatars
    resources :galleries
    resources :comments
    resources :articles do
      get "act(/:art_act)", :to => "Articles#act", :as => "act"
    end
    resources :sbmessages
  end

  resources :articles do
    resources :comments
  end
  match ':article' => 'Articles#show', :as => 'article' 
   root :to => "Home#index"
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  acts_as_list
  validates :title, :presence => true
  has_many :images
  has_many :galleries
  has_many :comments
  
  def to_param
    "#{id}-#{title.parameterize}"
  end

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AdminController
  def index
    @articles = Article.all(:order => :position)
  end
  def show
    @article = Article.find(params[:id])
  end
  def new
    @article = Article.new
    @image = Image.new
  end
  def edit
    @article = Article.find(params[:id])
    @image = Image.new
    @images = Image.all(:conditions => {:article_id => params[:id]})
  end
  def create
    @article = Article.new(params[:article])
    if @article.save
       @article.move_to_top
      redirect_to admin_articles_path
    else
      redirect_to admin_articles_path
    end
  end
  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      redirect_to admin_articles_path
    else
      redirect_to admin_articles_path
    end
  end
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to admin_articles_path
  end
  ##
  def act 
    @article = Article.find(params[:article_id])
    if (params[:art_act] == "true" || params[:art_act] == "false")
      respond_to do |format|
          if @article.update_attributes(:publish => params[:art_act])
            format.html {redirect_to(admin_articles_url)}        
          else
            format.html {redirect_to(admin_articles_url)}
          end
        end 
    elsif params[:art_act] == "up"
      respond_to do |format|
          if @article.move_higher
            format.html {redirect_to(admin_articles_url)}
          else
            format.html {redirect_to(admin_articles_url)}
          end
      end
    elsif params[:art_act] == "down"
      respond_to do |format|
          if @article.move_lower
            format.html {redirect_to(admin_articles_url)}
          else
            format.html {redirect_to(admin_articles_url)}
          end
      end
    end
  end

  ##
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
#    return render :text => "#{params.to_yaml}"
    if params[:article]
    @user_session = UserSession.new
    @users_online = User.find(:all, :order => 'last_request_at DESC', :limit => 10)
    @sbmessages = Sbmessage.all(:order => 'created_at DESC', :limit => 20)
  	@sbmessagesTOP = Sbmessage.all(:select => 'user_id, count(message) as top', :group => "user_id", :order => "top DESC", :limit => 5)
    else
    @articles = Articles.all(:order => :position)
  
    end
  end
  
  def show
 begin

     @article = Article.find(params[:article])
      rescue ActiveRecord::RecordNotFound
       return render :text => "ops"
     end
     @comments = Comment.all(:conditions => {:article_id => params[:article].chomp("-")[0].to_i}, :order => "created_at DESC").paginate(:per_page => 10, :page => params[:page])
     @user_session = UserSession.new
     @users_online = User.find(:all, :order => 'last_request_at DESC', :limit => 10)
     @sbmessages = Sbmessage.all(:order => 'created_at DESC', :limit => 20)
  	 @sbmessagesTOP = Sbmessage.all(:select => 'user_id, count(message) as top', :group => "user_id", :order => "top DESC", :limit => 5)
      
    end      
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/_form.html.erb
<%= form_for [:admin, @article] do |f| %>
<br />
  <p>
    <%= f.label :tytuł %>:<br />
    <%= f.text_field :title %><br />
    <%= f.label :tagi %>:<br />
    <%= f.text_field :tag %><br />
    <br />
    <%= f.label :zajawka %>:<br />
    <%= f.text_area :head, :class => "jquery_ckeditor" %><br />
    <%= f.label :treść %>:<br />
    <%= f.text_area :body, :class => "jquery_ckeditor" %><br />
    <%= f.submit %>
  </p>
<% end %>
  <%= form_for([:admin, @image], :html => {:multipart => true}) do |f| %>
    <p>
      <b><i>Image to Article/image</i></b><br />
      <%= f.file_field :photo %>
    </p>
    <p>
      Article id
      <%= f.hidden_field :article_id, :value => params[:id].chomp("-")[0].to_i%><br />
      Opis zdjęcia:<%= f.text_field :name %><br />
    </p>
    <p><%= f.submit "Dodaj zdjęcie"%>
    </p>
  <% end %>
<br />
<p>
  Dostępne rozmiary:<br />
:vsmall = 100x100,<br />
:thumb = 150x150,<br />
:small = 300x300,<br />
:oryginal => "800x600>",<br />
</p>
<% @images.each do |image| %>
<p>
<%= image_tag image.photo.url(:vsmall)%>
<div style="font-size: 10px;"><%= root_url + image.photo.url(:vsmall).sub("/", "")%></div>
</p>
<% end %>
<br /><br /><br /><br /><br /><br /><br />

app/views/admin/articles/edit.html.erb
<%= render 'form'%>
<%= link_to "Powrót", admin_articles_path %>

app/views/admin/articles/index.html.erb
<%= link_to "Dodaj artykuł", new_admin_article_path%>
<table>
  <tr>
    <th>#id</th>
    <th>pozycja</th>
    <th>tytuł</th>
    <th>publikacja?</th>
    <th colspan="3">Opcje</th>
  </tr>
  <% @articles.each do |article| %>
  <tr>
    <td>#<%= article.id%></td>
    <td><%= article.position%></td>
    <td><%= article.title%></td>
    <td><%= link_to("#{article.publish?}", article_act_path(article, "#{!article.publish?}")) %></td>
    <td><%= link_to("Up", article_act_path(article, "up"))%> |
        <%= link_to("Down", article_act_path(article, "down"))%></td>
    <td><%= link_to "Pokaż", admin_article_path(article)%></td>
    <td><%= link_to "Edytuj", edit_admin_article_path(article)%></td>
    <td><%= link_to "Usuń", admin_article_path(article), :method => :delete, :confirm => "Na pewno usunąć ten artykuł?" %></td>
  </tr>
  <% end %>
</table>

app/views/admin/articles/new.html.erb
<%= form_for [:admin, @article] do |f| %>
<br />
<p>
<%= f.label :tytuł %>:<br />
<%= f.text_field :title %><br />
<%= f.label :tagi %>:<br />
<%= f.text_field :tag %><br />
<br /><br /><br /><br />
<%= f.label :zajawka %>:<br />


<%= f.text_area :head, :class => "jquery_ckeditor" %><br />


<%= f.label :treść %>:<br />
<%= f.text_area :body, :class => "jquery_ckeditor" %><br />
<%= f.submit %>
</p>

<% end %>
<%= link_to "Powrót", admin_articles_path %>

app/views/admin/articles/show.html.erb
<%= @article.title%><br /><br />


        <%= @article.head.html_safe %><br />
        <%= @article.body.html_safe %>
        <br /><br />
        <%= link_to "Powrót", admin_articles_path %>