config/routes.rb
Vag::Application.routes.draw do

  match 'user/:user_id' => 'Users#show', :as => 'user'
  resources :user_sessions, :only =>[:new, :create, :destroy]
  resources :sbmessages, :only => [:new, :create]
  resources :avatars
  resources :users do
    resources :cargalleries do
      resources :carimages
    end
  end

  match 'admin', :to => 'Admin#index', :as => 'admin'      
  get 'login', :to => 'User_sessions#new', :as => 'login'
	match 'logout', :to => 'User_sessions#destroy', :as => 'logout'
  get 'register', :to => 'Users#new', :as => 'register'
  
   namespace :admin do    
    resources :users
    resources :images
    resources :avatars
    resources :galleries
    resources :comments
    resources :articles do
      get "act(/:art_act)", :to => "Articles#act", :as => "act"
    end
    resources :sbmessages
  end

  resources :articles do
    resources :comments
  end
  match ':article' => 'Articles#show', :as => 'article' 
   root :to => "Home#index"
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  acts_as_list
  validates :title, :presence => true
  has_many :images
  has_many :galleries
  has_many :comments
  
  def to_param
    "#{id}-#{title.parameterize}"
  end

end

app/models/avatar.rb
class Avatar < ActiveRecord::Base
  belongs_to :user
  
  has_attached_file :photo, :styles => { :vsmall => "70x60>",
                                         :small => "150x150>",
                                         :thumb => "250x250>",
                                         :original => "350x350>"},
 :url  => "/avatars/:id/:style/:basename.:extension",
 :path => ":rails_root/public/avatars/:id/:style/:basename.:extension"

validates_attachment_presence :photo
validates_attachment_size :photo, :less_than => 2.megabytes
validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

end

app/models/cargallery.rb
class Cargallery < ActiveRecord::Base
  belongs_to :user
  has_many :carimages
end

app/models/carimage.rb
class Carimage < ActiveRecord::Base
  belongs_to :cargallery
  acts_as_list :scope => :cargallery
  
    has_attached_file :photo, :styles => {
                                         :vsmall => "150x150>",
                                         :small => "300x300>",
                                         :thumb => "640x480>",
                                         :original => "800x600>"},
 :url  => "/carimages/:id/:style/:basename.:extension",
 :path => ":rails_root/public/carimages/:id/:style/:basename.:extension"

validates_attachment_presence :photo
validates_attachment_size :photo, :less_than => 5.megabytes
validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    validate :body, :presence => :true  
  
  belongs_to :article
  belongs_to :user
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  belongs_to :article
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :article
  belongs_to :gallery
#  acts_as_list :scope => :gallery
  
  has_attached_file :photo, :styles => { :vsmall => "100x100>",
                                         :thumb => "150x150>",
                                         :small => "300x300>",
                                         :oryginal => "800x600>"},
                  :url  => "/gallery/image/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/gallery/image/:id/:style/:basename.:extension"

validates_attachment_presence :photo
validates_attachment_size :photo, :less_than => 5.megabytes
validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/sbmessage.rb
class Sbmessage < ActiveRecord::Base
  validates :message, :presence => true
  validates :user_id, :presence => true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic 
  validate :username, :uniqueness => :true, :on =>  :create
  validate :email, :uniqueness => :true, :on => :create
  has_one :gallery
  has_one :cargallery
  has_one :avatar
  has_many :images
  has_many :comments
  belongs_to :role

  def to_param
    "#{username}"
  end

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  validate :username, :presence => true
  validate :password, :presence => true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @articles = Article.all(:order => :position, :conditions =>{:publish => true}).paginate(:per_page => 5, :page => params[:page])
    @user_session = UserSession.new
    @users_online = User.find(:all, :order => 'last_request_at DESC', :limit => 10)
    @sbmessages = Sbmessage.all(:order => 'created_at DESC', :limit => 20)
  	@sbmessagesTOP = Sbmessage.all(:select => 'user_id, count(message) as top', :group => "user_id", :order => "top DESC", :limit => 5)

  end
  
end

app/helpers/admin_helper.rb
module AdminHelper
  
    def javascript(*files)
      content_for(:head) { javascript_include_tag(*files) }
    end

    def stylesheet(*files)
      content_for(:head) { stylesheet_link_tag(*files) }
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
    def tag_content(tag)
    content_for(:tag) { "<meta name='keywords' content='#{tag}' />".html_safe}
  end

    def render_gallery(content)
    id = content.scan(/\{gallery=(\d+)\}/)
    if !id.nil?
      id.each do |id|
        partial_content = render :partial => 'share/gallery', :locals => {:id => id[0].to_i }
        content.sub! /\{gallery=\d+\}/, partial_content
      end
      return content.html_safe
    else
      content.gsub! /\{gallery=\d+\}/, ''
      content.html_safe
    end
  end  
    
  
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/carimages_helper.rb
module CarimagesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sbmessages_helper.rb
module SbmessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
panel admin

app/views/admin/share/_nav.html.erb
<!-- contentbox-->
	<div class="contentbox">
		<div class="contentbox_top">
			<div class="contentbox_top_left"></div>
			<div class="contentbox_top_center">Admin Nawigacja</div>
			<div class="contentbox_top_right"></div>
		</div>
		<div class="contentbox_left">
			<div class="contentbox_right">
				<div class="contentbox_center">
				<ul>
					<li><%= link_to "Panel administracyjny", admin_path %></li>
					<li><%= link_to "Artykuły", admin_articles_path %></li>
					<li><%= link_to "Shoutbox", admin_sbmessages_path %></li>
					<li><%= link_to "Komentarze", admin_comments_path %></li>
					<li><%= link_to "Użytkownicy", admin_users_path %></li>
				</ul>
				</div>
			</div>
		</div>

		<div class="contentbox_down">
			<div class="contentbox_down_left"></div>
			<div class="contentbox_down_center"></div>
			<div class="contentbox_down_right"></div>
		</div>
 </div>
<!-- contentbox! -->
<br />

app/views/share/_boxmessage.html.erb
<% @sbmessages.each do |message| %>
  <div class="webmessage_username"><%= message.user.username%>&nbsp;:&nbsp;&nbsp;
  <div style="display:inline;color:white;"><%= message.message %></div>
   </div>
<div class="webmessage_webmessage"></div>
<% end %>

app/views/share/_footer_inside.html.erb
footer footer footer footer footer footer footer footer footer
footer footer footer footer footer footer footer footer footer
footer footer footer footer footer footer footer footer footer
<%# (Time.now - User.last.last_request_at).to_i > User.last.timeout %>
<%# User.last.test %>

app/views/share/_login.html.erb
<% if current_user %>
				<ul>
		<li><%= link_to "Twój profil", user_path(current_user) %></li>
		<li><%= link_to "Edytuj profil", edit_user_path(current_user) %></li>
    <li><%= link_to "Galerie samochodów", user_cargalleries_path(current_user)%></li>
		<li><%= link_to "Logout", logout_path %></li>
				</ul>
<% else %>
   <%= form_for @user_session do |f| %>
    Login:<br />
    <%= f.text_field :username %><br />
    Hasło:<br />
    <%= f.password_field :password %>
    <%= f.submit "Zaloguj" %>
<% end %>
<br /><br />
<ul>
<li><%= link_to "Rejestracja", register_path, :class => "showmessage" %></li>
</ul>
			<% end %>

app/views/share/_main.html.erb
	<div class="mainbox">
		<div class="mainbox_top">
			<div class="mainbox_top_left"></div>
			<div class="mainbox_top_center"></div>
			<div class="mainbox_top_right"></div>
		</div>

		<div class="mainbox_left">
			<div class="mainbox_right">
				<div class="mainbox_center">
				test<br />test
      </div>
			</div>
		</div>

		<div class="mainbox_down">
			<div class="mainbox_down_left"></div>
			<div class="mainbox_down_center"></div>
			<div class="mainbox_down_right"></div>
		</div>
	</div>

app/views/share/_on_line.html.erb
<div class="box">
<% @users_online.each do |user| %>
	<div class="box_left"><%= user.username %></div>
	<div class="box_right">
		<%= distance_of_time_in_words_to_now(user.last_request_at) %>
</div>
	<br />
<% end %>
</div>

app/views/share/_shoutbox.html.erb
<div class="box">
<% if current_user %>
  <%= form_for :sbmessage, :url => {:controller => "sbmessages", :action => "create"}, :remote => true, :'data-type' => 'script', :html => {:id => "form_box"}  do |f| %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  <p>
    wiadomość:<br />
    <%= f.text_field :message %>
  </p>
  <p>
    <%= f.submit 'Dodaj' %>
  </p>
<% end %>
<br /><br />
<% end %>
<div id="shoutbox">
  <div id="shoutbox_messages">
    <% @sbmessages.each do |message| %>
    		<div class="webmessage_username"><%= message.user.username %>&nbsp;:&nbsp;&nbsp;
          <div style="display:inline;color:white;"><%= message.message %></div>
        </div>
        <div class="webmessage_webmessage"></div>
    <% end %>
  </div>
  </div>
</div>

app/views/share/_shoutboxtop.html.erb
<div id="shoutbox_top">
  <div class="box">
    <% @sbmessagesTOP.each do |toplist|%>
      <div class="top_box_left"><%= User.find(toplist.user_id).username%>:</div>
      <div class="top_box_right"><%= toplist.top %></div><br />
    <% end %>
    </div>
</div>

app/views/share/_site_a.html.erb
<!-- contentbox-->
	<div class="contentbox">
		<div class="contentbox_top">
			<div class="contentbox_top_left"></div>
			<div class="contentbox_top_center">Nawigacja</div>
			<div class="contentbox_top_right"></div>
		</div>
		<div class="contentbox_left">
			<div class="contentbox_right">
				<div class="contentbox_center">
				<ul>
					<li><%= link_to "Strona główna", root_path %></li>
				</ul>
				</div>
			</div>
		</div>

		<div class="contentbox_down">
			<div class="contentbox_down_left"></div>
			<div class="contentbox_down_center"></div>
			<div class="contentbox_down_right"></div>
		</div>
	</div>
<!-- contentbox! -->
<br />

app/views/share/_site_b.html.erb
<!-- contentbox-->
	<div class="contentbox">
		<div class="contentbox_top">
			<div class="contentbox_top_left"></div>
			<div class="contentbox_top_center">Login:&nbsp;
      <% if current_user %>
						<%= link_to current_user.username, user_path(current_user.username) %>
				<% end %>
			</div>
			<div class="contentbox_top_right"></div>
		</div>

		<div class="contentbox_left">
			<div class="contentbox_right">
				<div class="contentbox_center">
<%= render "share/login" %>
					</div>
			</div>
		</div>

		<div class="contentbox_down">
			<div class="contentbox_down_left"></div>
			<div class="contentbox_down_center"></div>
			<div class="contentbox_down_right"></div>
		</div>
	</div>
<!-- contentbox! -->
<br />
	<div class="contentbox">
		<div class="contentbox_top">
			<div class="contentbox_top_left"></div>
			<div class="contentbox_top_center">Shoutbox TOP</div>
			<div class="contentbox_top_right"></div>
		</div>

		<div class="contentbox_left">
			<div class="contentbox_right">
				<div class="contentbox_center">
<%= render "share/shoutboxtop" %>
				</div>
			</div>
		</div>

		<div class="contentbox_down">
			<div class="contentbox_down_left"></div>
			<div class="contentbox_down_center"></div>
			<div class="contentbox_down_right"></div>
		</div>
	</div>
<!-- contentbox! -->
<br />
	<div class="contentbox">
		<div class="contentbox_top">
			<div class="contentbox_top_left"></div>
			<div class="contentbox_top_center">Users on-line</div>
			<div class="contentbox_top_right"></div>
		</div>

		<div class="contentbox_left">
			<div class="contentbox_right">
				<div class="contentbox_center">
<%= render "share/on_line" %>
				</div>
			</div>
		</div>

		<div class="contentbox_down">
			<div class="contentbox_down_left"></div>
			<div class="contentbox_down_center"></div>
			<div class="contentbox_down_right"></div>
		</div>
	</div>
<!-- contentbox! -->
<br />
	<div class="contentbox">
		<div class="contentbox_top">
			<div class="contentbox_top_left"></div>
			<div class="contentbox_top_center">Shoutbox</div>
			<div class="contentbox_top_right"></div>
		</div>
		<div class="contentbox_left">
			<div class="contentbox_right">
				<div id="shoutbox_center">
<%= render "share/shoutbox" %>

				</div>
			</div>
		</div>

		<div class="contentbox_down">
			<div class="contentbox_down_left"></div>
			<div class="contentbox_down_center"></div>
			<div class="contentbox_down_right"></div>
		</div>
	</div>